baseURL = 'https://mhaidli.github.io/'
languageCode = 'en-us'
title = 'Abraham Mhaidli'
theme = 'classic'

[menu]
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 10
[[menu.main]]
  name = 'Publications'
  url = '/publications'
  weight = 30
[[menu.main]]
  name = 'Working with me'
  url = '/workingwithabraham'
  weight = 30
[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 30

# [[menu.main]]
#  name = 'Updates'
#  url = '/updates'
#  weight = 40
